# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChargeoverCli < Formula
  desc "ChargeOver developer CLI for installing, managing, and orchestrating a developer environment."
  homepage "https://chargeover.com/"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/v1.0.4/chargeover_1.0.4_Darwin_arm64.tar.gz"
      sha256 "623f9979b9571471fc21b4288edf4be015e350682ead7be5449455f54758f51d"

      def install
        bin.install "homebrew-chargeover-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/v1.0.4/chargeover_1.0.4_Darwin_x86_64.tar.gz"
      sha256 "a4637af58db483c76067112c216b43704a088d428544c940fe702d1d27b203f7"

      def install
        bin.install "homebrew-chargeover-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/v1.0.4/chargeover_1.0.4_Linux_arm64.tar.gz"
      sha256 "856aa49ccaf63671949567711582f85c40faeaf9a34e9916a1f30b5cb20d5eee"

      def install
        bin.install "homebrew-chargeover-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/v1.0.4/chargeover_1.0.4_Linux_x86_64.tar.gz"
      sha256 "69be3b9dc3ab5c5d10780fcbb6231a75dfc6d32f28405f10d45c50ceed220d5c"

      def install
        bin.install "homebrew-chargeover-cli"
      end
    end
  end

  test do
    system "#{bin}/chargeover-cli --help"
  end
end
