# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChargeoverCli < Formula
  desc "ChargeOver developer CLI for installing, managing, and orchestrating a developer environment."
  homepage "https://chargeover.com/"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/1.0.3/chargeover_1.0.3_Darwin_arm64.tar.gz"
      sha256 "b2ddd3779bd53b67e0e3495e414318828cfb9fb42f9bb318c5956af5ccea6944"

      def install
        bin.install "chargeover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/1.0.3/chargeover_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "4774ce051e077e1f0bf047253957ec6260ae98af2a9eb6698b6766e9307a82a5"

      def install
        bin.install "chargeover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/1.0.3/chargeover_1.0.3_Linux_arm64.tar.gz"
      sha256 "4aa172cf255629c1c1dc4b632313712b19ea33bd37811f87fc573e9e03587283"

      def install
        bin.install "chargeover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/1.0.3/chargeover_1.0.3_Linux_x86_64.tar.gz"
      sha256 "73496b5c08eace04c687d995f43c3e7299fa922c389edf32dec5c181d899f74a"

      def install
        bin.install "chargeover"
      end
    end
  end

  test do
    system "#{bin}/chargeover --help"
  end
end
