# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChargeoverCli < Formula
  desc "ChargeOver developer CLI for installing, managing, and orchestrating a developer environment."
  homepage "https://chargeover.com/"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/2.0.0/chargeover_2.0.0_Darwin_arm64.tar.gz"
      sha256 "e33ee2ee92a5e5fbe44b6c0e571b07fd7c47da1064ea04a171ec42b5dae97e71"

      def install
        bin.install "chargeover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/2.0.0/chargeover_2.0.0_Darwin_x86_64.tar.gz"
      sha256 "a91ea6be4c167d09ebfa702f5469896f45ee804d1dd4a0cca0bbc8f17fe9aa5b"

      def install
        bin.install "chargeover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/2.0.0/chargeover_2.0.0_Linux_arm64.tar.gz"
      sha256 "3ad47619f950e39e2fa5998d098fc95b95c934fc7dfd52a2a9f09068c0574bbd"

      def install
        bin.install "chargeover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chargeover/homebrew-chargeover-cli/releases/download/2.0.0/chargeover_2.0.0_Linux_x86_64.tar.gz"
      sha256 "b1f2c47de22b0d6895a1d5046738d3acece303c2e7126ca48a8b2b5c8d3a32fa"

      def install
        bin.install "chargeover"
      end
    end
  end

  test do
    system "#{bin}/chargeover --help"
  end
end
